# Generated by Django 5.1.6 on 2025-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountant',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='staff',
        ),
        migrations.AddField(
            model_name='claim',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
