# Generated by Django 5.1.6 on 2025-04-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_accountant_full_name_remove_claim_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='staff_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
