# Generated by Django 5.1.7 on 2025-03-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_acountant'),
    ]

    operations = [
        migrations.AddField(
            model_name='acountant',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
