# Generated by Django 5.1.6 on 2025-04-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_claim_staff_number_alter_claim_claim_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
