# Generated by Django 5.1.6 on 2025-04-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_claim_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='full_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
