# Generated by Django 5.1.7 on 2025-03-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_acountant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('accountant', 'Accountant')], default='staff', max_length=20),
        ),
        migrations.DeleteModel(
            name='Acountant',
        ),
    ]
