# Generated by Django 5.1.7 on 2025-03-16 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_staff_role_delete_acountant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=20)),
                ('payment_date', models.DateTimeField()),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.claim')),
            ],
        ),
    ]
