# Generated by Django 5.1.6 on 2025-04-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_claim_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='staff_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
