# Generated by Django 5.1.6 on 2025-03-18 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff'),
        ),
    ]
