# Generated by Django 5.1.6 on 2025-04-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_claim_staff_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
