# Generated by Django 5.1.6 on 2025-04-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_claim_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', models.FileField(blank=True, null=True, upload_to='documents/excel')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
