# Generated by Django 5.1.6 on 2025-03-23 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_staff_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('accountant', 'Accountant'), ('administrator', 'Administrator'), ('main_administrator', 'Main_Administrator')], default='accountant', max_length=20),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='core.claim')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.staff')),
            ],
        ),
    ]
