# Generated by Django 5.1.6 on 2025-03-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_staff_role_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_blocked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
