# Generated by Django 5.1.6 on 2025-03-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_staff_created_at_staff_updated_at_audittrail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('accountant', 'Accountant'), ('administrator', 'Administrator'), ('main_administrator', 'Main_Administrator')], default='accountant', max_length=20),
        ),
    ]
